apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    name: squid
    service: squid
spec:
  type: NodePort
  ports:
    - name: http
      port: 31290
      targetPort: http
      nodePort: 31290
  selector:
    service: squid
